from __future__ import annotations

import wave
from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"
TWO_SPEAKER_WAV = FIXTURES_DIR / "two_speaker_conversation.wav"


@pytest.fixture(scope="session")
def two_speaker_pcm() -> bytes:
    """Raw 16kHz mono 16-bit PCM bytes for the synthetic fixture generated by
    scripts/synthesize_test_audio.py. Regenerate it with:
        python -m scripts.synthesize_test_audio
    """
    if not TWO_SPEAKER_WAV.exists():
        pytest.skip(f"fixture missing: {TWO_SPEAKER_WAV} -- run `python -m scripts.synthesize_test_audio`")
    with wave.open(str(TWO_SPEAKER_WAV), "rb") as wf:
        return wf.readframes(wf.getnframes())


class FakeTranscriber:
    """A Transcriber that returns a canned string for any non-silent-looking
    audio, and an empty string for near-silent audio -- fast, deterministic,
    no model download. Used everywhere except tests/live.
    """

    def __init__(self, text: str = "hello world") -> None:
        self.text = text
        self.calls: list[int] = []  # records len(audio) per call, for assertions

    def transcribe(self, audio) -> str:  # noqa: ANN001
        self.calls.append(len(audio))
        return self.text
