from __future__ import annotations

from asr.streaming import FRAME_BYTES, VadSegmenter


def test_pure_silence_yields_no_segments():
    seg = VadSegmenter()
    silence = b"\x00\x00" * 16_000 * 2  # 2s of digital silence
    events = list(seg.push(silence)) + list(seg.flush())
    assert events == []


def test_two_speaker_fixture_yields_four_alternating_segments(two_speaker_pcm):
    """End-to-end against the real synthetic fixture (speaker A/B/A/B with
    700ms silence gaps, generated by scripts/synthesize_test_audio.py). This
    is the same check performed manually against the actual webrtcvad output
    while building this module -- see the repo README for the exact numbers
    observed there.
    """
    seg = VadSegmenter()
    events = []
    # Feed in odd, non-frame-aligned chunk sizes on purpose: real audio
    # sources (a WebSocket, a microphone callback) don't hand you frames
    # pre-aligned to webrtcvad's required 30ms boundary.
    chunk_size = 3200
    for i in range(0, len(two_speaker_pcm), chunk_size):
        events.extend(seg.push(two_speaker_pcm[i : i + chunk_size]))
    events.extend(seg.flush())

    assert len(events) == 4
    # Segments must be in chronological order with no overlap.
    for a, b in zip(events, events[1:], strict=False):
        assert a.end_ts <= b.start_ts
    for e in events:
        assert e.end_ts > e.start_ts
        assert len(e.pcm16) > 0
        assert len(e.pcm16) % 2 == 0  # whole int16 samples only


def test_arbitrary_chunk_sizes_dont_lose_or_duplicate_audio():
    """Feeding one byte at a time vs. one giant chunk must produce the same
    total amount of buffered speech -- the frame re-alignment logic in
    push() must not drop or double-count bytes at chunk boundaries.
    """
    import numpy as np

    # A single loud, sustained tone -- guaranteed classified as speech by
    # webrtcvad for its whole duration, so segment length is a direct proxy
    # for "how many bytes did the segmenter actually see."
    t = np.arange(16_000) / 16_000.0  # 1s
    tone = (0.8 * np.sin(2 * np.pi * 180 * t)).astype(np.float32)
    pcm = (tone * 32767).astype(np.int16).tobytes()

    def run(chunk_size: int):
        seg = VadSegmenter(silence_timeout_ms=10_000)  # never trigger silence-finalize
        buf = bytearray()
        for i in range(0, len(pcm), chunk_size):
            for s in seg.push(pcm[i : i + chunk_size]):
                buf.extend(s.pcm16)
        for s in seg.flush():
            buf.extend(s.pcm16)
        return len(buf)

    one_byte_at_a_time = run(1)
    one_big_chunk = run(len(pcm))
    # Equal up to the frame-alignment granularity (< 1 frame of trailing
    # partial bytes can differ depending on chunking).
    assert abs(one_byte_at_a_time - one_big_chunk) < FRAME_BYTES


def test_short_blip_below_min_segment_is_dropped():
    """A couple of loud frames surrounded by silence -- shorter than
    min_segment_ms -- should be treated as a VAD false-positive and dropped,
    not emitted as a segment.
    """
    import numpy as np

    seg = VadSegmenter(min_segment_ms=250)  # default
    t = np.arange(int(16_000 * 0.06)) / 16_000.0  # 60ms, well under 250ms
    blip = (0.8 * np.sin(2 * np.pi * 180 * t)).astype(np.float32)
    pcm = (blip * 32767).astype(np.int16).tobytes()
    silence = b"\x00\x00" * 16_000  # 1s trailing silence to force finalize

    events = list(seg.push(pcm)) + list(seg.push(silence)) + list(seg.flush())
    assert events == []
